# Generated by Django 3.1.1 on 2025-08-01 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('street_number', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=200)),
                ('suburb', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=10)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(default='Australia', max_length=100)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('levels', models.IntegerField()),
                ('land_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'unique_together': {('street_number', 'street_name', 'suburb', 'postcode')},
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Property', 'Property'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial')], max_length=20)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Completed'), (4, 'Cancelled')], default=1)),
                ('method_of_access', models.IntegerField(choices=[(1, 'Keysafe'), (2, 'Agent'), (3, 'Occupant'), (4, 'Other')])),
                ('access_details', models.TextField(blank=True)),
                ('listing_agent', models.CharField(max_length=50)),
                ('occupant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('occupant_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('access_other', models.TextField(blank=True, null=True)),
                ('package', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_team_members', models.ManyToManyField(related_name='assigned_jobs', to='jobs.TeamMember')),
                ('contacts', models.ManyToManyField(related_name='jobs', to='jobs.Contact')),
                ('products', models.ManyToManyField(related_name='jobs', to='jobs.Product')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.property')),
            ],
        ),
    ]
